-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admins_comunidade
(
    id_comunidade integer NOT NULL,
    login character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_comunidade_login PRIMARY KEY (id_comunidade, login)
);

CREATE TABLE IF NOT EXISTS public.amizades
(
    id_amizade serial NOT NULL,
    login_amigo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    login_usuario character varying(20) COLLATE pg_catalog."default" NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_amizades PRIMARY KEY (id_amizade)
);

CREATE TABLE IF NOT EXISTS public.comunidades
(
    id_comunidade serial NOT NULL,
    nome_comunidade character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_id_comunidade PRIMARY KEY (id_comunidade)
);

CREATE TABLE IF NOT EXISTS public.mensagens
(
    id_mensagem serial NOT NULL,
    conteudo text COLLATE pg_catalog."default" NOT NULL,
    data_envio timestamp without time zone NOT NULL,
    vizualizada boolean NOT NULL,
    receptor character varying(20) COLLATE pg_catalog."default" NOT NULL,
    emissor character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_id_mensagem PRIMARY KEY (id_mensagem)
);

CREATE TABLE IF NOT EXISTS public.mensagens_usuario
(
    id_mensagem integer NOT NULL,
    login character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_mensagem_usuario PRIMARY KEY (id_mensagem, login)
);

CREATE TABLE IF NOT EXISTS public.topicos
(
    id_topico serial NOT NULL,
    nome_topico character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT pk_id_topico PRIMARY KEY (id_topico)
);

CREATE TABLE IF NOT EXISTS public.topicos_comunidades
(
    id_topico integer NOT NULL,
    id_comunidade integer NOT NULL,
    CONSTRAINT pk_topicos_comunidades PRIMARY KEY (id_topico, id_comunidade)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    login character varying(20) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cargo character varying(20) COLLATE pg_catalog."default",
    nome_usuario character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT pk_login PRIMARY KEY (login)
);

CREATE TABLE IF NOT EXISTS public.usuarios_comunidades
(
    login character varying(20) COLLATE pg_catalog."default" NOT NULL,
    id_comunidade integer NOT NULL,
    CONSTRAINT pk_login_id_comunidade PRIMARY KEY (login, id_comunidade)
);

ALTER TABLE IF EXISTS public.admins_comunidade
    ADD CONSTRAINT fk_id_comunidade_admins FOREIGN KEY (id_comunidade)
    REFERENCES public.comunidades (id_comunidade) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.admins_comunidade
    ADD CONSTRAINT fk_login_admins FOREIGN KEY (login)
    REFERENCES public.usuarios (login) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.amizades
    ADD CONSTRAINT fk_amizades_usuarios1 FOREIGN KEY (login_amigo)
    REFERENCES public.usuarios (login) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.amizades
    ADD CONSTRAINT fk_amizades_usuarios2 FOREIGN KEY (login_usuario)
    REFERENCES public.usuarios (login) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mensagens
    ADD CONSTRAINT fk_emissor FOREIGN KEY (emissor)
    REFERENCES public.usuarios (login) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mensagens
    ADD CONSTRAINT fk_receptor FOREIGN KEY (receptor)
    REFERENCES public.usuarios (login) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mensagens_usuario
    ADD CONSTRAINT fk_id_mensagem_m_u FOREIGN KEY (id_mensagem)
    REFERENCES public.mensagens (id_mensagem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mensagens_usuario
    ADD CONSTRAINT fk_id_usuario_m_u FOREIGN KEY (login)
    REFERENCES public.usuarios (login) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.topicos_comunidades
    ADD CONSTRAINT fk_id_comunidade_t_c FOREIGN KEY (id_comunidade)
    REFERENCES public.comunidades (id_comunidade) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.topicos_comunidades
    ADD CONSTRAINT fk_id_topico_t_c FOREIGN KEY (id_topico)
    REFERENCES public.topicos (id_topico) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.usuarios_comunidades
    ADD CONSTRAINT fk_id_comunidade FOREIGN KEY (id_comunidade)
    REFERENCES public.comunidades (id_comunidade) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.usuarios_comunidades
    ADD CONSTRAINT fk_login_u_c FOREIGN KEY (login)
    REFERENCES public.usuarios (login) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

INSERT INTO usuarios (login, senha, cargo, nome_usuario) VALUES ('admin', '0000', 'Admin', 'Admin');

END;